# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef706ede8aaa61e768f03777cedabf6080cdd972fc0ea6629b70bcac6706ec0e1d97c64ba4d50ae76b90b132b0c2a2c0892994176b0551c1fc5db916524222ea

test:
  secret_key_base: ce4332e7464fbacce09d77671b596f121a9b5e8e603c4f6dd9603ecf4cc6045a0073fea1ab86b4cd051c87f60e5e9070260b74a34565d25e48b20f0784462235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
